# Generated by Django 5.0.6 on 2024-05-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('added_date', models.DateField()),
                ('deadline', models.DateField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
