# Generated by Django 5.0.6 on 2024-05-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcard',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='medcard',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medcard',
            name='count',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='medcard',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
