# Generated by Django 5.0.6 on 2024-05-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_medcard_pharmacy_medcard_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medcard',
            old_name='name',
            new_name='dori_nomi',
        ),
        migrations.RenameField(
            model_name='medcard',
            old_name='type',
            new_name='ichish_turi',
        ),
        migrations.RenameField(
            model_name='medcard',
            old_name='description',
            new_name='maxal',
        ),
        migrations.RenameField(
            model_name='medcard',
            old_name='price',
            new_name='narx',
        ),
        migrations.RenameField(
            model_name='medcard',
            old_name='added_date',
            new_name='tayyorlandi',
        ),
        migrations.RenameField(
            model_name='medcard',
            old_name='deadline',
            new_name='yaroqlilik',
        ),
    ]
